version: '3.3'
services:
  # Eureka Server      
  eurekasvc:
    build: EurekaServer
    container_name: eurekasrvr
    image: bmc/eurekasrvr:1.0.0
    ports:
      - "8761:8761"
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
    hostname: eureka-service

  # Doctor service
  bookingsvc:
    build: DoctorService
    container_name: doctorsvc
    image: bmc/doctorsvc:1.0.0
    ports:
      - "8081:8081"
    networks:
      - microservicesnet
    environment:
      DOCTOR_SERVICE_PORT: 8081
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DATABASE: bmc
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      S3_ACCESS_KEY: AKIAQ5V4DQNUG6UCGY4P
      S3_SECRET_KEY: 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
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # User service
  usersvc:
    build: UserService
    container_name: usersvc
    image: bmc/usersvc:1.0.0
    ports:
      - "8082:8082"
    networks:
      - microservicesnet
    environment:
      USER_SERVICE_PORT: 8082
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DATABASE: bmc
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      S3_ACCESS_KEY: AKIAQ5V4DQNUG6UCGY4P
      S3_SECRET_KEY: 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
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # Appointment service
  appointmentsvc:
    build: AppointmentService
    container_name: appointmentsvc
    image: bmc/appointmentsvc:1.0.0
    ports:
      - "8083:8083"
    networks:
      - microservicesnet
    environment:
      APPOINTMENT_SERVICE_PORT: 8083
      USER_SERVICE_PORT: 8082
      MYSQL_HOST: localhost
      MYSQL_HOST_PORT: 3306
      MySQL_DATABASE: Consultation
      MYSQL_USER: root
      MYSQL_PASSWORD: root@mysql
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DATABASE: bmc
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # Payment service
  paymentsvc:
    build: PaymentService
    container_name: paymentsvc
    image: bmc/paymentsvc:1.0.0
    ports:
      - "8084:8084"
    networks:
      - microservicesnet
    environment:
      PAYMENT_SERVICE_PORT: 8084
      MYSQL_HOST: localhost
      MYSQL_HOST_PORT: 3306
      MYSQL_DATABASE: Consultation
      MYSQL_USER: root
      MYSQL_PASSWORD: root@mysql
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # Rating service
  ratingsvc:
    build: RatingService
    container_name: ratingsvc
    image: bmc/ratingsvc:1.0.0
    ports:
      - "8085:8085"
    networks:
      - microservicesnet
    environment:
      RATING_SERVICE_PORT: 8085
      MYSQL_HOST: localhost
      MYSQL_HOST_PORT: 3306
      MYSQL_DATABASE: Consultation
      MYSQL_USER: root
      MYSQL_PASSWORD: root@mysql
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # Notification service
  notificationsvc:
    build: NotificationService
    container_name: notificationsvc
    image: bmc/notificationsvc:1.0.0
    ports:
      - "8086:8086"
    networks:
      - microservicesnet
    environment:
      NOTIFICATION_SERVICE_PORT: 8086
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      KAFKA_HOST: localhost
      KAFKA_HOST_PORT: 9092
      SES_ACCESSKEY: AKIAQ5V4DQNUG6UCGY4P
      SES_SECRETKEY: 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
      SES_FROM_EMAIL: vinod.patil.engineer@gmail.com
      eureka.client.serviceUrl.defaultZone: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

  # API Gateway
  gatewaysvc:
    build: API-gateway
    container_name: apigatewaysvc
    image: bmc/apigatewaysvc:1.0.0
    ports:
      - "8080:8080"
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: eureka-service
      EUREKA_HOST_PORT: 8761
      eureka.client.serviceUrl.defaultZon: http://eurekasvc:8761/eureka/
    depends_on:
      - eurekasvc

networks:
  microservicesnet:
    driver: bridge