spring:
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:${EUREKA_HOST_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}